### PR TITLE
fix the clean script

### PR DESCRIPTION
**Pull request by biplovbhandari**

### CODE REVIEW

**Comment by flavour** [comment]
I like this line...I use it a lot.
Now sure it gives an error if the script isn't found which isn't nice...perhaps test for existence of file first & only execute if found?

**Comment by biplovbhandari** [comment]
What do you use it for? Would be good to know if there is something helpful with that. Wondering is that script available in trunk?

**Comment by flavour** [comment]
I use it for postpop of data...usually the Polygons.
Not in trunk as always unique per-deployment

**Comment by biplovbhandari** [comment]
@flavour checked for existence of file

**Comment by flavour** [comment]
Great, thanks :)

**Pull request merged**
